name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: '6.0.x'
    - name: Build with dotnet
      run: cd src/Dijkstra.NET && dotnet build --configuration Release --framework net6.0 --runtime linux-x64


